rootProject.name = 'TheGaffer'

include 'thegaffer-core', 'thegaffer-bukkit', 'thegaffer-velocity'

project(':thegaffer-core').projectDir = file('thegaffer-core')
project(':thegaffer-bukkit').projectDir = file('thegaffer-bukkit')
project(':thegaffer-velocity').projectDir = file('thegaffer-velocity')
