name: ${project.artifactId}
main: com.mcmiddleearth.thegaffer.TheGaffer
version: ${project.version}
api-version: 1.15
website: ${project.url}
authors: [meggawatts, DonoA, Eriol_Eandur, Planetology, Fraspace5]
description: Job API for MCME.
softdepend: [DiscordSRV, VentureChat]
author: meggawatts
commands:
  createjob:
    description: Launches a job creation conversation can be done with /job start or /job create
    usage: |
           /createjob
  job:
    usage: |
            /job stop <jobname>
            /job check
            /job archive
            /job join <jobname>
            /job warpto <jobname>
            /job info <jobname>
            /job admit <player>
            /job create
            /job start
            /job admin
  jobadmin:
    description: Launches the jobadmin conversation can also be done with /job admin
    usage: |
           /jobadmin