plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow'
//    id 'xyz.jpenilla.run-velocity' version '3.0.2'
    id 'xyz.jpenilla.run-velocity' version '2.3.1'
}

group = rootProject.group
version = rootProject.version

dependencies {
  implementation project(':thegaffer-core')
  compileOnly 'com.velocitypowered:velocity-api:3.4.0-SNAPSHOT'
  annotationProcessor 'com.velocitypowered:velocity-api:3.4.0-SNAPSHOT'
}

jar {
    enabled = false
}

shadowJar {
    archiveBaseName.set('thegaffer-velocity')
    archiveVersion.set(rootProject.version)
    archiveClassifier.set('')
    mergeServiceFiles()
}

artifacts {
    archives shadowJar
}

tasks {
    runVelocity {
        // Configure the Velocity version for our task.
        // This is the only required configuration besides applying the plugin.
        // Your plugin's jar (or shadowJar if present) will be used automatically.
        velocityVersion("3.4.0-SNAPSHOT")
    }
}